spring:
  config:
    activate:
      on-profile: default
  application:
      name: spring-eureka-server-default

server:
  port: 8759

eureka:
  instance:
    hostname: eureka-server-default.com
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false  # Disable self-preservation mode

---
spring:
  config:
    activate:
      on-profile: eureka-paris
  application:
      name: spring-eureka-server-cluster

server:
  port: 8760

eureka:
  instance:
    hostname: eureka-server-paris.com
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-london.com:8761/eureka/,http://eureka-server-istanbul.com:8762/eureka/
  server:
    enableSelfPreservation: false  # Disable self-preservation mode

---

spring:
  config:
    activate:
      on-profile: eureka-london
  application:
    name: spring-eureka-server-cluster

server:
  port: 8761

eureka:
  instance:
    hostname: spring-eureka-server-london.com
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-paris.com:8760/eureka/,http://eureka-server-istanbul.com:8762/eureka/
  server:
    enableSelfPreservation: false  # Disable self-preservation mode

---
spring:
  config:
    activate:
      on-profile: eureka-istanbul
  application:
    name: spring-eureka-server-cluster

server:
  port: 8762

eureka:
  instance:
    hostname: spring-eureka-server-london.com
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-paris.com:8760/eureka/,http://eureka-server-london.com:8761/eureka/

  server:
    enableSelfPreservation: false  # Disable self-preservation mode